### ISSUE TITLE
Download Counts stuck?

### ISSUE THREAD

**Issue by jacktasia** [melpa/melpa#4231]
The `download_counts.json` file seems to be stuck with the same values for at least the last 24 hours, but I am pretty sure it started 5-6 days ago. I am guessing the `process_log.py` file is expecting an old (nginx? and not caddy) version of the logs.

**Comment by purcell** [comment]
We're back on nginx now, so that's not the problem, but I'll take a look.

**Comment by purcell** [comment]
The updated nginx config was mistakenly logging to a temporary location. I've fixed that, I'm running those missed logs back through our log processor, so the download stats should eventually come right again. Thanks for the heads-up!

**Comment by purcell** [comment]
Looking at the set-up, I'm actually also wondering if we can end up missing stats due to log rotation... we'll have to investigate that. We keep all the old logs so can reprocess across all time if necessary.

**Comment by purcell** [comment]
I didn't note the counts before fixing this - can you confirm this is fixed please?

**Comment by jacktasia** [comment]
Yup. It's definitely fixed now. Here's the screenshot I took yesterday at 1:17PM California time when I thought was something up, when it was still the same today I opened the ticket.

![melpa-9-9-117pm](https://cloud.githubusercontent.com/assets/31308/18414550/70a2eec6-7782-11e6-9df8-277957707638.png)

**Comment by purcell** [comment]
Awesome, thanks!

**Comment by milkypostman** [comment]
i've intended to rewrite the parser for this but time...

**Comment by jacktasia** [comment]
The download counts seem to be stuck again. Here's a screenshot I took 24 hours ago:

![image](https://cloud.githubusercontent.com/assets/31308/18621465/c3db5f7c-7dd8-11e6-9d74-a7358c85950d.png)

All the counts are still the same today.

**Comment by milkypostman** [comment]
investigating.

**Comment by milkypostman** [comment]
something is weird with nginx. for some reason it had stopped writing logs at all since the 12th. I killed the job and it started writing again. lets leave this open and monitor.

**Comment by purcell** [comment]
There's probably a logrotate job which isn't correctly signalling the nginx to reopen its logs.

**Comment by jacktasia** [comment]
FWIW it has been at least ~28 hours since the download counts have changed.

![image](https://cloud.githubusercontent.com/assets/31308/18775012/89aba864-8113-11e6-8c2d-f0cb56331b87.png)

**Comment by purcell** [comment]
Will try to take a look over the weekend.

**Comment by milkypostman** [comment]
ok should be permanently fixed. somehow the PID file in nginx config mismatched with log rotate. sorry.

**Comment by alphapapa** [comment]
Thanks, @milkypostman.  Just curious, will download counts be lost from during this period?

**Comment by milkypostman** [comment]
Unfortunately yes it looks like nginx just stopped writing them since there
last rotation.
