### ISSUE TITLE
Melpa Stable issue

### ISSUE THREAD

**Issue by cslux** [melpa/melpa#6583]
[RTags](https://github.com/Andersbakken/rtags) contributer here. Melpa Stable still offers an old version of the =rtags*= packages (https://stable.melpa.org/#/?q=rtags). We are already at version **v2.35**.

Do you have any idea what's going on here?

Thanks!

**Comment by milkypostman** [comment]
It shows version 3.23 for me. Not clear why it’s detecting that version. My
guess is there is some odd tag in the repo that is confusing the build.
I’ll have to look more tonight.

**Comment by cslux** [comment]
Very likely we pushed an invalid tag (v3.23) and removed it later. I guess only when the new tag is >v3.23 a new Melpa Stable packages gets created?

**Comment by milkypostman** [comment]
Yeah we can delete it as well but users with the 3.23 version will not get
updates until a new version greater than 3.23 is released or they
re-install the package.

Unfortunately this is the downside of automatic releases.

**Comment by cslux** [comment]
It is broken anyway. So please delete it.

Thank you Donald!

**Comment by milkypostman** [comment]
@cslux thanks for letting me know about the issue. I deleted all temporary files and all packages for `*rtags*`. things should be better in <12 hours ... please let me know if by tomorrow at this time things have not resolved.
