### ISSUE TITLE
Issue installing packages via melpa

### ISSUE THREAD

**Issue by cgideon** [melpa/melpa#7340]
I'm new to using Emacs and am trying to install dotnet and powershell for Emacs on Mac using Melpa, I have the below configured in my init.el

<img width="661" alt="Screen Shot 2021-01-03 at 7 23 23 PM" src="https://user-images.githubusercontent.com/3642672/103493817-2baebf00-4df9-11eb-8431-4f930cb5bbe8.png">

M-x package-initialize seems to work, at least I don't see any errors. But when I try to do an M-x package-install dotnet I get the below error that I'm not sure how to fix.

<img width="829" alt="Screen Shot 2021-01-03 at 7 20 40 PM" src="https://user-images.githubusercontent.com/3642672/103493790-fd30e400-4df8-11eb-9b75-2aee4cb13a68.png">

**Comment by purcell** [comment]
Using https should fix this.

**Comment by purcell** [comment]
PS. I don't think there's anything useful that's only in the `tromey` archive and not in GNU ELPA or MELPA, so you can drop that one. It's a relic.

**Comment by purcell** [comment]
ALSO: You're using the same URL for both MELPA and MELPA Stable, might want to fix the URL for the latter. :-)

**Comment by cgideon** [comment]
@purcell Thanks! I made those changes you suggested, I'm still receiving the same error though when doing 
M-x package-install

**Comment by cgideon** [comment]
Not sure what was wrong with that init.el, I ended up just deleting it and am going to rebuild it how I want it to work. I'm able to install packages now without issue in my new init.el
